//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://www.dbnet.cl/getPDF64", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.dbnet.cl/getPDF64", ConfigurationName="ServiceReference1.getPDF64Soap")]
    public interface getPDF64Soap {
        
        // CODEGEN: Generating message contract since element name rutt from namespace http://www.dbnet.cl/getPDF64 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dbnet.cl/getPDF64/get_pdf", ReplyAction="*")]
        ConsoleApplication1.ServiceReference1.get_pdfResponse get_pdf(ConsoleApplication1.ServiceReference1.get_pdfRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dbnet.cl/getPDF64/get_pdf", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.get_pdfResponse> get_pdfAsync(ConsoleApplication1.ServiceReference1.get_pdfRequest request);
        
        // CODEGEN: Generating message contract since element name sRutt from namespace http://www.dbnet.cl/getPDF64 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dbnet.cl/getPDF64/get_pdf_sucursal", ReplyAction="*")]
        ConsoleApplication1.ServiceReference1.get_pdf_sucursalResponse get_pdf_sucursal(ConsoleApplication1.ServiceReference1.get_pdf_sucursalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dbnet.cl/getPDF64/get_pdf_sucursal", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.get_pdf_sucursalResponse> get_pdf_sucursalAsync(ConsoleApplication1.ServiceReference1.get_pdf_sucursalRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class get_pdfRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="get_pdf", Namespace="http://www.dbnet.cl/getPDF64", Order=0)]
        public ConsoleApplication1.ServiceReference1.get_pdfRequestBody Body;
        
        public get_pdfRequest() {
        }
        
        public get_pdfRequest(ConsoleApplication1.ServiceReference1.get_pdfRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dbnet.cl/getPDF64")]
    public partial class get_pdfRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rutt;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string folio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string doc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string monto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string fecha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ruttt;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool Merito;
        
        public get_pdfRequestBody() {
        }
        
        public get_pdfRequestBody(string rutt, string folio, string doc, string monto, string fecha, string ruttt, bool Merito) {
            this.rutt = rutt;
            this.folio = folio;
            this.doc = doc;
            this.monto = monto;
            this.fecha = fecha;
            this.ruttt = ruttt;
            this.Merito = Merito;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class get_pdfResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="get_pdfResponse", Namespace="http://www.dbnet.cl/getPDF64", Order=0)]
        public ConsoleApplication1.ServiceReference1.get_pdfResponseBody Body;
        
        public get_pdfResponse() {
        }
        
        public get_pdfResponse(ConsoleApplication1.ServiceReference1.get_pdfResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dbnet.cl/getPDF64")]
    public partial class get_pdfResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleApplication1.ServiceReference1.ArrayOfString get_pdfResult;
        
        public get_pdfResponseBody() {
        }
        
        public get_pdfResponseBody(ConsoleApplication1.ServiceReference1.ArrayOfString get_pdfResult) {
            this.get_pdfResult = get_pdfResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class get_pdf_sucursalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="get_pdf_sucursal", Namespace="http://www.dbnet.cl/getPDF64", Order=0)]
        public ConsoleApplication1.ServiceReference1.get_pdf_sucursalRequestBody Body;
        
        public get_pdf_sucursalRequest() {
        }
        
        public get_pdf_sucursalRequest(ConsoleApplication1.ServiceReference1.get_pdf_sucursalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dbnet.cl/getPDF64")]
    public partial class get_pdf_sucursalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sRutt;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sFolio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sDoc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sMonto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sFecha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sRuttt;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool bMerito;
        
        public get_pdf_sucursalRequestBody() {
        }
        
        public get_pdf_sucursalRequestBody(string sRutt, string sFolio, string sDoc, string sMonto, string sFecha, string sRuttt, bool bMerito) {
            this.sRutt = sRutt;
            this.sFolio = sFolio;
            this.sDoc = sDoc;
            this.sMonto = sMonto;
            this.sFecha = sFecha;
            this.sRuttt = sRuttt;
            this.bMerito = bMerito;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class get_pdf_sucursalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="get_pdf_sucursalResponse", Namespace="http://www.dbnet.cl/getPDF64", Order=0)]
        public ConsoleApplication1.ServiceReference1.get_pdf_sucursalResponseBody Body;
        
        public get_pdf_sucursalResponse() {
        }
        
        public get_pdf_sucursalResponse(ConsoleApplication1.ServiceReference1.get_pdf_sucursalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dbnet.cl/getPDF64")]
    public partial class get_pdf_sucursalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleApplication1.ServiceReference1.ArrayOfString get_pdf_sucursalResult;
        
        public get_pdf_sucursalResponseBody() {
        }
        
        public get_pdf_sucursalResponseBody(ConsoleApplication1.ServiceReference1.ArrayOfString get_pdf_sucursalResult) {
            this.get_pdf_sucursalResult = get_pdf_sucursalResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface getPDF64SoapChannel : ConsoleApplication1.ServiceReference1.getPDF64Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getPDF64SoapClient : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReference1.getPDF64Soap>, ConsoleApplication1.ServiceReference1.getPDF64Soap {
        
        public getPDF64SoapClient() {
        }
        
        public getPDF64SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public getPDF64SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public getPDF64SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public getPDF64SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference1.get_pdfResponse ConsoleApplication1.ServiceReference1.getPDF64Soap.get_pdf(ConsoleApplication1.ServiceReference1.get_pdfRequest request) {
            return base.Channel.get_pdf(request);
        }
        
        public ConsoleApplication1.ServiceReference1.ArrayOfString get_pdf(string rutt, string folio, string doc, string monto, string fecha, string ruttt, bool Merito) {
            ConsoleApplication1.ServiceReference1.get_pdfRequest inValue = new ConsoleApplication1.ServiceReference1.get_pdfRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference1.get_pdfRequestBody();
            inValue.Body.rutt = rutt;
            inValue.Body.folio = folio;
            inValue.Body.doc = doc;
            inValue.Body.monto = monto;
            inValue.Body.fecha = fecha;
            inValue.Body.ruttt = ruttt;
            inValue.Body.Merito = Merito;
            ConsoleApplication1.ServiceReference1.get_pdfResponse retVal = ((ConsoleApplication1.ServiceReference1.getPDF64Soap)(this)).get_pdf(inValue);
            return retVal.Body.get_pdfResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.get_pdfResponse> ConsoleApplication1.ServiceReference1.getPDF64Soap.get_pdfAsync(ConsoleApplication1.ServiceReference1.get_pdfRequest request) {
            return base.Channel.get_pdfAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.get_pdfResponse> get_pdfAsync(string rutt, string folio, string doc, string monto, string fecha, string ruttt, bool Merito) {
            ConsoleApplication1.ServiceReference1.get_pdfRequest inValue = new ConsoleApplication1.ServiceReference1.get_pdfRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference1.get_pdfRequestBody();
            inValue.Body.rutt = rutt;
            inValue.Body.folio = folio;
            inValue.Body.doc = doc;
            inValue.Body.monto = monto;
            inValue.Body.fecha = fecha;
            inValue.Body.ruttt = ruttt;
            inValue.Body.Merito = Merito;
            return ((ConsoleApplication1.ServiceReference1.getPDF64Soap)(this)).get_pdfAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference1.get_pdf_sucursalResponse ConsoleApplication1.ServiceReference1.getPDF64Soap.get_pdf_sucursal(ConsoleApplication1.ServiceReference1.get_pdf_sucursalRequest request) {
            return base.Channel.get_pdf_sucursal(request);
        }
        
        public ConsoleApplication1.ServiceReference1.ArrayOfString get_pdf_sucursal(string sRutt, string sFolio, string sDoc, string sMonto, string sFecha, string sRuttt, bool bMerito) {
            ConsoleApplication1.ServiceReference1.get_pdf_sucursalRequest inValue = new ConsoleApplication1.ServiceReference1.get_pdf_sucursalRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference1.get_pdf_sucursalRequestBody();
            inValue.Body.sRutt = sRutt;
            inValue.Body.sFolio = sFolio;
            inValue.Body.sDoc = sDoc;
            inValue.Body.sMonto = sMonto;
            inValue.Body.sFecha = sFecha;
            inValue.Body.sRuttt = sRuttt;
            inValue.Body.bMerito = bMerito;
            ConsoleApplication1.ServiceReference1.get_pdf_sucursalResponse retVal = ((ConsoleApplication1.ServiceReference1.getPDF64Soap)(this)).get_pdf_sucursal(inValue);
            return retVal.Body.get_pdf_sucursalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.get_pdf_sucursalResponse> ConsoleApplication1.ServiceReference1.getPDF64Soap.get_pdf_sucursalAsync(ConsoleApplication1.ServiceReference1.get_pdf_sucursalRequest request) {
            return base.Channel.get_pdf_sucursalAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.get_pdf_sucursalResponse> get_pdf_sucursalAsync(string sRutt, string sFolio, string sDoc, string sMonto, string sFecha, string sRuttt, bool bMerito) {
            ConsoleApplication1.ServiceReference1.get_pdf_sucursalRequest inValue = new ConsoleApplication1.ServiceReference1.get_pdf_sucursalRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference1.get_pdf_sucursalRequestBody();
            inValue.Body.sRutt = sRutt;
            inValue.Body.sFolio = sFolio;
            inValue.Body.sDoc = sDoc;
            inValue.Body.sMonto = sMonto;
            inValue.Body.sFecha = sFecha;
            inValue.Body.sRuttt = sRuttt;
            inValue.Body.bMerito = bMerito;
            return ((ConsoleApplication1.ServiceReference1.getPDF64Soap)(this)).get_pdf_sucursalAsync(inValue);
        }
    }
}
